// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSvkfOUqUdhgsGqEFwWWaqmZAm4E-NFAI',
    appId: '1:165355428371:web:2934c31bfdf609b52afde6',
    messagingSenderId: '165355428371',
    projectId: 'finanshub-aa04c',
    authDomain: 'finanshub-aa04c.firebaseapp.com',
    storageBucket: 'finanshub-aa04c.appspot.com',
    measurementId: 'G-78L3GBLQXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJD2AyqB0rB42NN8646iZ32_5TzEUILsI',
    appId: '1:165355428371:android:030901d65afeced62afde6',
    messagingSenderId: '165355428371',
    projectId: 'finanshub-aa04c',
    storageBucket: 'finanshub-aa04c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYwGASpy0yMg5bbuNt2A5_Qcp2NcL-a0',
    appId: '1:165355428371:ios:a425fab6b4bf1bd82afde6',
    messagingSenderId: '165355428371',
    projectId: 'finanshub-aa04c',
    storageBucket: 'finanshub-aa04c.appspot.com',
    iosBundleId: 'com.finans.hub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYwGASpy0yMg5bbuNt2A5_Qcp2NcL-a0',
    appId: '1:165355428371:ios:a425fab6b4bf1bd82afde6',
    messagingSenderId: '165355428371',
    projectId: 'finanshub-aa04c',
    storageBucket: 'finanshub-aa04c.appspot.com',
    iosBundleId: 'com.finans.hub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSvkfOUqUdhgsGqEFwWWaqmZAm4E-NFAI',
    appId: '1:165355428371:web:660929a9732fcea42afde6',
    messagingSenderId: '165355428371',
    projectId: 'finanshub-aa04c',
    authDomain: 'finanshub-aa04c.firebaseapp.com',
    storageBucket: 'finanshub-aa04c.appspot.com',
    measurementId: 'G-X3THD9Z2YC',
  );
}
